sources:
  - GitHubClientTestSample
  - GitHubClientTestSampleUITests
templates:
  - GitHubClientTestSampleUITests/Template/AutoPrivatePropertyAccessible.stencil
output:
  # https://bugs.swift.org/browse/SR-631
  GitHubClientTestSampleUITests/Gen/zzz.Sourcery.out.swift
